[package]
name = "ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
# pretty_env_logger = "0.4"

tokio = { version = "1.25", features = ["full"] }
bytes = "1.4"

# stick = "0.12"
stick = { path = "stick/stick" }

tui = "0.19.0"
crossterm = "0.26.0"
eyre = "0.6"
tui-logger = "0.8"
