name = "Thrustmaster Warthog Throttle"
type = "flight"

[remap]
Throttle = "Slew"
Trigger = "Mouse"
ActionM = "MicPush"
Bumper = "MicUp"
ActionR = "MicLeft"
ActionL = "MicDown"
Pinky = "MicRight"
1 = "SpeedbrakeForward"
2 = "SpeedbrakeBackward"
3 = "BoatForward"
4 = "BoatBackward"
5 = "ChinaForward"
6 = "ChinaBackward"
7 = "PinkyForward"
8 = "PinkyBackward"
9 = "ThrottleButton"
10 = "EngineFuelFlowL"
11 = "EngineFuelFlowR"
12 = "EngineMotorL"
13 = "EngineMotorR"
14 = "Apu"
15 = "LandingGearSilence"
16 = "FlapsUp"
17 = "FlapsDown"
18 = "Eac"
19 = "RadarAltimeter"
20 = "AutopilotToggle"
21 = "AutopilotPath"
22 = "AutopilotAlt"
25 = "EngineIgnitionL"
26 = "EngineIgnitionR"
JoyX = { event = "MouseX", max = 1024 }
JoyY = { event = "MouseY", max = 1024 }
JoyZ = { event = "ThrottleR", max = 16339 }
CamZ = { event = "ThrottleL", max = 16339 }
